### ISSUE TITLE
Support sentry APM

### ISSUE THREAD

**Issue by hieuhtr** [quarkiverse/quarkus-logging-sentry#17]
Hi guys, 

I'm using Quarkus and sentry for error tracking, now I also want to use sentry APM on JDBC tracing too. I tried to config like this but it's not working, seems we do not have wrapper config on `sentry-jul`

```
quarkus:
    log:
        sentry:
            ~: true
            dsn: "http://xxxxxxxxxx"
            environment: production
            level: ERROR
            minimum-event-level: ERROR
            minimum-breadcrumb-level: DEBUG
            in-app-packages: '*'
            enable-tracing: true
            traces-sample-rate: 0.2
```

Do you guys have any plan on supporting this? 

Thank you!
